component TOF "PLC style TOF delay timer";

pin in bit IN;       //timer input
pin in unsigned T;   //time delay in base periods
pin out bit OUT;     //delayed signal
pin out unsigned ET; //elapsed time
pin out unsigned state;		//statemachine var

function _;
license "GPL"; // indicates GPL v2 or later
;;


if(state==0){
	if(IN){
		state=10;
		OUT=1;
		ET=0;
	}
}

if(state==10){
	if(!IN)state=20;
}

if(state==20){
	if(ET++ >= T){
		OUT=0;
		state=0;
	}
}