/* Autogenerated by /usr/bin/halcompile on Mon Jul 30 21:44:40 2018 -- do not edit */
#include "rtapi.h"
#ifdef RTAPI
#include "rtapi_app.h"
#endif
#include "rtapi_string.h"
#include "rtapi_errno.h"
#include "hal.h"
#include "rtapi_math64.h"

static int comp_id;

#ifdef MODULE_INFO
MODULE_INFO(linuxcnc, "component:pokeys:PoKeys IO driver, by Mit Zot");
MODULE_INFO(linuxcnc, "pin:in-#:bit:41:out::None:None");
MODULE_INFO(linuxcnc, "pin:ain-#:s32:8:out::None:None");
MODULE_INFO(linuxcnc, "pin:enc-#:s32:4:out::None:None");
MODULE_INFO(linuxcnc, "pin:out-#:bit:7:in::None:None");
MODULE_INFO(linuxcnc, "pin:err:bit:0:out::None:None");
MODULE_INFO(linuxcnc, "pin:devSerial:u32:0:in::None:None");
MODULE_INFO(linuxcnc, "pin:alive:bit:0:out::None:None");
MODULE_INFO(linuxcnc, "pin:cycletime:u32:0:in::40000:None");
MODULE_INFO(linuxcnc, "license:GPL");
MODULE_LICENSE("GPL");
#endif // MODULE_INFO


struct __comp_state {
    struct __comp_state *_next;
    hal_bit_t *in[41];
    hal_s32_t *ain[8];
    hal_s32_t *enc[4];
    hal_bit_t *out[7];
    hal_bit_t *err;
    hal_u32_t *devSerial;
    hal_bit_t *alive;
    hal_u32_t *cycletime;
};
#include <stdlib.h>
struct __comp_state *__comp_first_inst=0, *__comp_last_inst=0;

static int __comp_get_data_size(void);
#undef TRUE
#define TRUE (1)
#undef FALSE
#define FALSE (0)
#undef true
#define true (1)
#undef false
#define false (0)

static int export(char *prefix, long extra_arg) {
    int r = 0;
    int j = 0;
    int sz = sizeof(struct __comp_state) + __comp_get_data_size();
    struct __comp_state *inst = hal_malloc(sz);
    memset(inst, 0, sz);
    for(j=0; j < (41); j++) {
        r = hal_pin_bit_newf(HAL_OUT, &(inst->in[j]), comp_id,
            "%s.in-%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (8); j++) {
        r = hal_pin_s32_newf(HAL_OUT, &(inst->ain[j]), comp_id,
            "%s.ain-%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (4); j++) {
        r = hal_pin_s32_newf(HAL_OUT, &(inst->enc[j]), comp_id,
            "%s.enc-%01d", prefix, j);
        if(r != 0) return r;
    }
    for(j=0; j < (7); j++) {
        r = hal_pin_bit_newf(HAL_IN, &(inst->out[j]), comp_id,
            "%s.out-%01d", prefix, j);
        if(r != 0) return r;
    }
    r = hal_pin_bit_newf(HAL_OUT, &(inst->err), comp_id,
        "%s.err", prefix);
    if(r != 0) return r;
    r = hal_pin_u32_newf(HAL_IN, &(inst->devSerial), comp_id,
        "%s.devSerial", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_OUT, &(inst->alive), comp_id,
        "%s.alive", prefix);
    if(r != 0) return r;
    r = hal_pin_u32_newf(HAL_IN, &(inst->cycletime), comp_id,
        "%s.cycletime", prefix);
    if(r != 0) return r;
    *(inst->cycletime) = 40000;
    if(__comp_last_inst) __comp_last_inst->_next = inst;
    __comp_last_inst = inst;
    if(!__comp_first_inst) __comp_first_inst = inst;
    return 0;
}
static int default_count=1, count=0;
char *names[16] = {0,};
int rtapi_app_main(void) {
    int r = 0;
    int i;
    comp_id = hal_init("pokeys");
    if(comp_id < 0) return comp_id;
    if(count && names[0]) {
        rtapi_print_msg(RTAPI_MSG_ERR,"count= and names= are mutually exclusive\n");
        return -EINVAL;
    }
    if(!count && !names[0]) count = default_count;
    if(count) {
        for(i=0; i<count; i++) {
            char buf[HAL_NAME_LEN + 1];
            rtapi_snprintf(buf, sizeof(buf), "pokeys.%d", i);
            r = export(buf, i);
            if(r != 0) break;
       }
    } else {
        int max_names = sizeof(names)/sizeof(names[0]);
        for(i=0; (i < max_names) && names[i]; i++) {
            if (strlen(names[i]) < 1) {
                rtapi_print_msg(RTAPI_MSG_ERR, "names[%d] is invalid (empty string)\n", i);
                r = -EINVAL;
                break;
            }
            r = export(names[i], i);
            if(r != 0) break;
       }
    }
    if(r) {
        hal_exit(comp_id);
    } else {
        hal_ready(comp_id);
    }
    return r;
}

void rtapi_app_exit(void) {
    hal_exit(comp_id);
}
static void user_mainloop(void);
int argc=0; char **argv=0;
int main(int argc_, char **argv_) {
    argc = argc_; argv = argv_;


    if(rtapi_app_main() < 0) return 1;
    user_mainloop();
    rtapi_app_exit();
    return 0;
}

#undef FUNCTION
#define FUNCTION(name) static void name(struct __comp_state *__comp_inst, long period)
#undef EXTRA_SETUP
#define EXTRA_SETUP() static int extra_setup(struct __comp_state *__comp_inst, char *prefix, long extra_arg)
#undef EXTRA_CLEANUP
#define EXTRA_CLEANUP() static void extra_cleanup(void)
#undef fperiod
#define fperiod (period * 1e-9)
#undef in
#define in(i) (*(__comp_inst->in[i]))
#undef ain
#define ain(i) (*(__comp_inst->ain[i]))
#undef enc
#define enc(i) (*(__comp_inst->enc[i]))
#undef out
#define out(i) (0+*(__comp_inst->out[i]))
#undef err
#define err (*__comp_inst->err)
#undef devSerial
#define devSerial (0+*__comp_inst->devSerial)
#undef alive
#define alive (*__comp_inst->alive)
#undef cycletime
#define cycletime (0+*__comp_inst->cycletime)
#undef FOR_ALL_INSTS
#define FOR_ALL_INSTS() struct __comp_state *__comp_inst; for(__comp_inst = __comp_first_inst; __comp_inst; __comp_inst = __comp_inst->_next)


#line 46 "./pokeys.comp"

#include "PoKeysLib.h"
#include <unistd.h>   /* UNIX standard function definitions */

sPoKeysDevice * dev=NULL;
int i=0;

void user_mainloop(void) 
{ 
    while(0xb){
       FOR_ALL_INSTS() {
         int OK = 0; 
         while(devSerial==0)usleep(500000); 
	 while(dev == NULL){
                    dev = PK_ConnectToDeviceWSerial(devSerial, 2000);  //waits for usb device
                    if(dev == NULL) err=1;
         }

	 alive=1; 
         OK  = PK_DigitalIOGet(dev) == PK_OK; //gets IO data and checks return value 
         //OK &= PK_AnalogIOGet(dev) == PK_OK;
         //OK &= PK_EncoderValuesGet(dev) == PK_OK
	 if (OK){  
		err=0;
		for(i=1;i<41;i++)in(i)=!dev->Pins[i].DigitalValueGet;             //just transfers values
		//for(i=0;i<8;i++)ain(i)=(dev->Pins[41 + i].AnalogValue>>4)/(512/200);
                //for(i=0;i<4;i++)enc(i)=dev->Encoders[i].encoderValue;
                //for(i=0;i<7;i++)dev->Pins[48 + i].DigitalValueSet = out(i);
                //PK_DigitalIOSet(dev);
	 }
         else{             		  //on connection error
		PK_DisconnectDevice(dev);
		dev=NULL;  		  //tries to reconnect
		err=1;
		for(i=0;i<41;i++)in(i)=0;
		for(i=0;i<3;i++)ain(i)=0;
                rtapi_print_msg(RTAPI_MSG_ERR, "PoKeys comp error\n");
	 }
	 alive=0;
	usleep(cycletime); 
        }
    }

    exit(0);
}
static int __comp_get_data_size(void) { return 0; }
