#!/bin/bash

. '/home/cnc/LinuxCNC/linuxcnc/scripts/rip-environment'
halcmd setp spgb.M10 1
halcmd setp spgb.M11 0

count="0"
while [ $(halcmd getp spgb.M10) == "TRUE" ]
do
    count=$[$count+1]
    if [ $count -gt 50 ]
    then
        echo "---timeout M10!!"
        exit -1
    fi
    sleep 0.1s
done

exit 0
