#!/bin/bash

. '/home/cnc/LinuxCNC/linuxcnc/scripts/rip-environment'
halcmd setp spgb.M43 1
halcmd setp spgb.M42 0
halcmd setp spgb.M41 0


count="0"
while [ $(halcmd getp spgb.M43) == "TRUE" ]
do
    count=$[$count+1]
    if [ $count -gt 50 ]
    then
        echo "---timeout M143!!"
        exit -1
    fi
    sleep 0.1s
done

exit 0
