#!/bin/bash


exit 0








count="0"
while [ $(halcmd getp halui.spindle.is-on) == "TRUE" ]
do
    sleep 0.1s
    count=$[$count+1]
    if [ $count -gt 50 ]
    then
        exit -1
    fi
done

exit 0
